import { NextRequest, NextResponse } from 'next/server';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';

/**
 * Feature Request Management API
 *
 * GET /api/claude-builder/features?projectName=MyProject
 * - Returns all feature requests from FEATURE_REQUESTS.md
 *
 * PATCH /api/claude-builder/features
 * - Update feature request status
 * - Body: { projectName, featureId, status, rejectionReason? }
 *
 * DELETE /api/claude-builder/features
 * - Delete a feature request
 * - Body: { projectName, featureId }
 */

interface FeatureRequest {
  id: string;
  title: string;
  description: string;
  status: 'pending' | 'approved' | 'rejected' | 'implemented';
  priority: 'high' | 'medium' | 'low';
  requestedBy: string;
  requestedAt: string;
  context?: {
    page?: string;
    userIntent?: string;
  };
  approvedAt?: string;
  rejectedAt?: string;
  rejectionReason?: string;
}

function getProjectPath(projectName: string): string {
  const homeDir = os.homedir();
  const sanitizedName = projectName.replace(/[^a-zA-Z0-9-_]/g, '-');
  return path.join(homeDir, 'Projects', 'BuildRunnerProjects', sanitizedName);
}

function parseFeaturesFile(content: string): FeatureRequest[] {
  const features: FeatureRequest[] = [];
  const featureBlocks = content.split(/^## Feature Request #/gm).slice(1);

  featureBlocks.forEach((block) => {
    const lines = block.split('\n');
    const idMatch = lines[0]?.match(/^(\d+)/);
    if (!idMatch) return;

    const id = idMatch[1];
    const feature: Partial<FeatureRequest> = {
      id,
      context: {},
    };

    // Parse fields
    lines.forEach((line) => {
      const trimmedLine = line.trim();

      if (trimmedLine.startsWith('**Title:**')) {
        feature.title = trimmedLine.replace('**Title:**', '').trim();
      } else if (trimmedLine.startsWith('**Description:**')) {
        feature.description = trimmedLine.replace('**Description:**', '').trim();
      } else if (trimmedLine.startsWith('**Status:**')) {
        feature.status = trimmedLine.replace('**Status:**', '').trim().toLowerCase() as FeatureRequest['status'];
      } else if (trimmedLine.startsWith('**Priority:**')) {
        feature.priority = trimmedLine.replace('**Priority:**', '').trim().toLowerCase() as FeatureRequest['priority'];
      } else if (trimmedLine.startsWith('**Requested By:**')) {
        feature.requestedBy = trimmedLine.replace('**Requested By:**', '').trim();
      } else if (trimmedLine.startsWith('**Requested:**')) {
        feature.requestedAt = trimmedLine.replace('**Requested:**', '').trim();
      } else if (trimmedLine.startsWith('**Approved:**')) {
        feature.approvedAt = trimmedLine.replace('**Approved:**', '').trim();
      } else if (trimmedLine.startsWith('**Rejected:**')) {
        feature.rejectedAt = trimmedLine.replace('**Rejected:**', '').trim();
      } else if (trimmedLine.startsWith('**Rejection Reason:**')) {
        feature.rejectionReason = trimmedLine.replace('**Rejection Reason:**', '').trim();
      } else if (trimmedLine.startsWith('**Page:**')) {
        feature.context!.page = trimmedLine.replace('**Page:**', '').trim();
      } else if (trimmedLine.startsWith('**User Intent:**')) {
        feature.context!.userIntent = trimmedLine.replace('**User Intent:**', '').trim();
      }
    });

    if (feature.id && feature.title) {
      features.push(feature as FeatureRequest);
    }
  });

  return features;
}

function writeFeaturesFile(projectPath: string, features: FeatureRequest[]): void {
  let content = '# Feature Requests\n\n';
  content += '> Auto-generated by Claude Builder chat widget\n\n';
  content += '---\n\n';

  features.forEach((feature) => {
    content += `## Feature Request #${feature.id}\n\n`;
    content += `**Title:** ${feature.title}\n`;
    content += `**Description:** ${feature.description}\n`;
    content += `**Status:** ${feature.status}\n`;
    content += `**Priority:** ${feature.priority}\n`;
    content += `**Requested By:** ${feature.requestedBy}\n`;
    content += `**Requested:** ${feature.requestedAt}\n`;

    if (feature.context?.page) {
      content += `**Page:** ${feature.context.page}\n`;
    }
    if (feature.context?.userIntent) {
      content += `**User Intent:** ${feature.context.userIntent}\n`;
    }
    if (feature.approvedAt) {
      content += `**Approved:** ${feature.approvedAt}\n`;
    }
    if (feature.rejectedAt) {
      content += `**Rejected:** ${feature.rejectedAt}\n`;
    }
    if (feature.rejectionReason) {
      content += `**Rejection Reason:** ${feature.rejectionReason}\n`;
    }

    content += '\n---\n\n';
  });

  fs.writeFileSync(path.join(projectPath, 'FEATURE_REQUESTS.md'), content, 'utf8');
}

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const projectName = searchParams.get('projectName');

    if (!projectName) {
      return NextResponse.json(
        { error: 'projectName is required' },
        { status: 400 }
      );
    }

    const projectPath = getProjectPath(projectName);
    const featuresPath = path.join(projectPath, 'FEATURE_REQUESTS.md');

    if (!fs.existsSync(featuresPath)) {
      return NextResponse.json({ features: [] });
    }

    const content = fs.readFileSync(featuresPath, 'utf8');
    const features = parseFeaturesFile(content);

    return NextResponse.json({ features });
  } catch (error) {
    console.error('[Claude Builder] Get features error:', error);
    return NextResponse.json(
      {
        error: 'Failed to fetch feature requests',
        details: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    );
  }
}

export async function PATCH(request: NextRequest) {
  try {
    const { projectName, featureId, status, rejectionReason } = await request.json();

    if (!projectName || !featureId || !status) {
      return NextResponse.json(
        { error: 'projectName, featureId, and status are required' },
        { status: 400 }
      );
    }

    const projectPath = getProjectPath(projectName);
    const featuresPath = path.join(projectPath, 'FEATURE_REQUESTS.md');

    if (!fs.existsSync(featuresPath)) {
      return NextResponse.json({ error: 'Features file not found' }, { status: 404 });
    }

    const content = fs.readFileSync(featuresPath, 'utf8');
    const features = parseFeaturesFile(content);

    const feature = features.find((f) => f.id === featureId);
    if (!feature) {
      return NextResponse.json({ error: 'Feature not found' }, { status: 404 });
    }

    feature.status = status;
    if (status === 'approved') {
      feature.approvedAt = new Date().toISOString();

      // Add to PRD.md
      const prdPath = path.join(projectPath, 'PRD.md');
      if (fs.existsSync(prdPath)) {
        let prdContent = fs.readFileSync(prdPath, 'utf8');

        // Find the end of the document
        const featureSection = `\n\n## New Feature: ${feature.title}\n\n${feature.description}\n\n**Priority:** ${feature.priority}\n**Approved:** ${feature.approvedAt}\n`;

        prdContent += featureSection;
        fs.writeFileSync(prdPath, prdContent, 'utf8');
      }
    } else if (status === 'rejected') {
      feature.rejectedAt = new Date().toISOString();
      feature.rejectionReason = rejectionReason;
    }

    writeFeaturesFile(projectPath, features);

    return NextResponse.json({ success: true, feature });
  } catch (error) {
    console.error('[Claude Builder] Update feature error:', error);
    return NextResponse.json(
      {
        error: 'Failed to update feature request',
        details: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    );
  }
}

export async function DELETE(request: NextRequest) {
  try {
    const { projectName, featureId } = await request.json();

    if (!projectName || !featureId) {
      return NextResponse.json(
        { error: 'projectName and featureId are required' },
        { status: 400 }
      );
    }

    const projectPath = getProjectPath(projectName);
    const featuresPath = path.join(projectPath, 'FEATURE_REQUESTS.md');

    if (!fs.existsSync(featuresPath)) {
      return NextResponse.json({ error: 'Features file not found' }, { status: 404 });
    }

    const content = fs.readFileSync(featuresPath, 'utf8');
    const features = parseFeaturesFile(content);

    const filteredFeatures = features.filter((f) => f.id !== featureId);

    if (filteredFeatures.length === features.length) {
      return NextResponse.json({ error: 'Feature not found' }, { status: 404 });
    }

    writeFeaturesFile(projectPath, filteredFeatures);

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('[Claude Builder] Delete feature error:', error);
    return NextResponse.json(
      {
        error: 'Failed to delete feature request',
        details: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    );
  }
}
