export interface AppConfig {
  appType: 'web' | 'mobile';
  framework: 'nextjs' | 'expo' | 'react-native';
  navigationType: 'tabs' | 'stack' | 'drawer' | 'none';
  platforms: ('ios' | 'android' | 'web')[];
  appName: string;
  description: string;
}

export class AppTypeDetector {
  /**
   * Detect app configuration from PRD content
   */
  detectFromPRD(prd: string, buildPlan?: string): AppConfig {
    const content = `${prd} ${buildPlan || ''}`.toLowerCase();

    // Detect app type
    const isMobile = this.detectMobileApp(content);
    const isWeb = this.detectWebApp(content);

    // Detect framework
    let framework: AppConfig['framework'];
    if (isMobile) {
      framework = content.includes('expo') ? 'expo' : 'react-native';
    } else {
      framework = 'nextjs';
    }

    // Detect navigation type
    const navigationType = this.detectNavigationType(content);

    // Detect platforms
    const platforms = this.detectPlatforms(content, isMobile);

    // Extract app name and description
    const appName = this.extractAppName(prd);
    const description = this.extractDescription(prd);

    return {
      appType: isMobile ? 'mobile' : 'web',
      framework,
      navigationType,
      platforms,
      appName,
      description,
    };
  }

  /**
   * Detect if app is mobile from content
   */
  private detectMobileApp(content: string): boolean {
    const mobileKeywords = [
      'ios app',
      'android app',
      'mobile app',
      'react native',
      'expo',
      'swiftui',
      'xcode',
      'app store',
      'play store',
      'smartphone',
      'mobile application',
      'ios application',
      'android application',
    ];

    return mobileKeywords.some(keyword => content.includes(keyword));
  }

  /**
   * Detect if app is web from content
   */
  private detectWebApp(content: string): boolean {
    const webKeywords = [
      'web app',
      'website',
      'dashboard',
      'admin panel',
      'next.js',
      'nextjs',
      'web application',
      'browser',
      'responsive',
    ];

    return webKeywords.some(keyword => content.includes(keyword));
  }

  /**
   * Detect navigation type from content
   */
  private detectNavigationType(content: string): AppConfig['navigationType'] {
    if (content.includes('tab') || content.includes('bottom navigation')) {
      return 'tabs';
    }
    if (content.includes('drawer') || content.includes('sidebar')) {
      return 'drawer';
    }
    if (content.includes('stack') || content.includes('navigation flow')) {
      return 'stack';
    }
    return 'tabs'; // Default for mobile, none for web handled elsewhere
  }

  /**
   * Detect target platforms
   */
  private detectPlatforms(content: string, isMobile: boolean): ('ios' | 'android' | 'web')[] {
    const platforms: ('ios' | 'android' | 'web')[] = [];

    if (isMobile) {
      if (content.includes('ios') || content.includes('iphone') || content.includes('app store')) {
        platforms.push('ios');
      }
      if (content.includes('android') || content.includes('play store')) {
        platforms.push('android');
      }
      // If no specific platform mentioned, support both
      if (platforms.length === 0) {
        platforms.push('ios', 'android');
      }
    } else {
      platforms.push('web');
    }

    return platforms;
  }

  /**
   * Extract app name from PRD
   */
  private extractAppName(prd: string): string {
    // Look for "# AppName" or "## AppName" at start
    const headerMatch = prd.match(/^#+ (.+)$/m);
    if (headerMatch) {
      return headerMatch[1].trim();
    }

    // Look for "App Name:" or "Application:" patterns
    const nameMatch = prd.match(/(?:app name|application|project):\s*(.+)$/im);
    if (nameMatch) {
      return nameMatch[1].trim();
    }

    return 'Generated App';
  }

  /**
   * Extract description from PRD
   */
  private extractDescription(prd: string): string {
    // Look for first paragraph after header
    const lines = prd.split('\n').filter(line => line.trim());

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      // Skip headers
      if (line.startsWith('#')) continue;
      // Skip bullets
      if (line.match(/^[-*\d.]/)) continue;
      // First real paragraph
      if (line.length > 20) {
        return line.trim().slice(0, 200);
      }
    }

    return 'Generated by BuildRunner';
  }

  /**
   * Detect from component files (fallback method)
   */
  detectFromComponents(components: any[]): Partial<AppConfig> {
    const hasReactNative = components.some(c =>
      c.code?.includes('react-native') ||
      c.code?.includes('View') ||
      c.code?.includes('StyleSheet')
    );

    const hasNextJS = components.some(c =>
      c.code?.includes('next/') ||
      c.type === 'page'
    );

    return {
      appType: hasReactNative ? 'mobile' : 'web',
      framework: hasReactNative ? 'expo' : 'nextjs',
    };
  }
}
