/**
 * Generates BUILD_DOC.md from PRD
 * This document provides complete project context to Claude
 */

export interface PRDData {
  productName: string;
  productIdea: string;
  prdSections?: Record<string, any>;
  targetAudience?: string;
  features?: Array<{ name: string; description: string }>;
}

export class BuildDocGenerator {

  /**
   * Generate BUILD_DOC.md from PRD
   */
  generate(prd: PRDData): string {
    const doc = `# Build Document - ${prd.productName}

*Generated by BuildRunner + Claude CLI*
*Date: ${new Date().toLocaleString()}*

---

## Project Overview

**Product Name:** ${prd.productName}

**Description:**
${prd.productIdea}

${prd.targetAudience ? `**Target Audience:** ${prd.targetAudience}` : ''}

---

## Features

${this.formatFeatures(prd)}

---

## Technical Stack

**Framework:** Next.js 14 (App Router)
**Runtime:** React 18
**Styling:** Tailwind CSS 4
**Component Library:** shadcn/ui + Radix UI
**Animations:** Framer Motion
**Forms:** React Hook Form + Zod
**State Management:** React Context / Zustand
**API:** Next.js API Routes
**Database:** Prisma + PostgreSQL (if needed)
**Auth:** NextAuth.js (if needed)
**Deployment:** Vercel

---

## Architecture Patterns

**Frontend:**
- Server Components by default
- Client Components only when needed (interactivity, hooks)
- App Router file-based routing
- API routes in app/api/
- Shared components in src/components/

**Styling:**
- Tailwind CSS-first approach
- Design tokens from DESIGN_SYSTEM.md
- Mobile-first responsive design
- Dark mode support (when appropriate)

**Data Fetching:**
- Server-side data fetching in Server Components
- React Server Components for data hydration
- Client-side with SWR/React Query when needed

**Code Quality:**
- TypeScript strict mode
- ESLint + Prettier
- Component-level unit tests
- E2E tests with Playwright

---

## Development Guidelines

### Code Style
- Functional components with hooks
- TypeScript for all files
- Descriptive variable names
- JSDoc comments for functions
- Error boundaries for error handling

### Component Structure
\`\`\`tsx
'use client' // Only if needed

import { ... }

interface Props {
  // TypeScript props
}

/**
 * Component description
 */
export default function ComponentName({ ...props }: Props) {
  // Hooks first
  // Event handlers
  // Render
}
\`\`\`

### API Route Structure
\`\`\`typescript
import { NextRequest, NextResponse } from 'next/server'

export async function GET(request: NextRequest) {
  try {
    // Implementation
    return NextResponse.json({ data })
  } catch (error) {
    return NextResponse.json(
      { error: 'Error message' },
      { status: 500 }
    )
  }
}
\`\`\`

---

## Design Standards

Follow the design system in DESIGN_SYSTEM.md:
- Use design tokens (not hardcoded colors)
- Consistent spacing scale
- Typography hierarchy
- Component patterns

**Quality Bar:** Linear / Stripe level polish
- Smooth animations
- Loading states
- Error handling
- Empty states
- Responsive layouts

---

## File Organization

\`\`\`
src/
  app/
    (routes)/
      page.tsx
      layout.tsx
    api/
      [endpoint]/
        route.ts
  components/
    ui/          # shadcn/ui components
    [feature]/   # Feature-specific components
  lib/
    utils.ts
    hooks/
    types/
\`\`\`

---

## Success Criteria

- ✅ All features implemented
- ✅ TypeScript strict mode passing
- ✅ ESLint passing
- ✅ Responsive on mobile/tablet/desktop
- ✅ Accessible (WCAG 2.1 AA)
- ✅ Fast loading (< 3s initial load)
- ✅ Beautiful UI (matches design system)
- ✅ All API endpoints functional
- ✅ Error handling throughout

---

*This document is used as context for all Claude CLI build tasks*
`;

    return doc;
  }

  /**
   * Format features from PRD
   */
  private formatFeatures(prd: PRDData): string {
    if (prd.features && prd.features.length > 0) {
      return prd.features
        .map((f, i) => `### ${i + 1}. ${f.name}\n\n${f.description}\n`)
        .join('\n');
    }

    if (prd.prdSections && prd.prdSections.features) {
      const features = prd.prdSections.features;
      if (Array.isArray(features)) {
        return features
          .map((f: any, i: number) => `### ${i + 1}. ${f.title || f.name}\n\n${f.description}\n`)
          .join('\n');
      }
    }

    return '*Features will be added during build planning*';
  }
}

export const buildDocGenerator = new BuildDocGenerator();
