/**
 * Design System Generator V2
 * Creates comprehensive design system from PRD for Claude builds
 */

export interface DesignSystemConfig {
  productName: string;
  targetAudience?: string;
  industryVertical?: string;
  emotionalTone?: string;
}

export class DesignSystemGeneratorV2 {

  /**
   * Generate complete design system
   */
  generate(config: DesignSystemConfig): string {
    return `# Design System - ${config.productName}

*Generated by BuildRunner for Claude CLI Builds*

---

## Brand Identity

**Target Audience:** ${config.targetAudience || 'Modern consumers, 25-45 years old'}
**Industry:** ${config.industryVertical || 'Technology/SaaS'}
**Emotional Tone:** ${config.emotionalTone || 'Professional, trustworthy, modern'}

**Design Philosophy:**
- Clean and minimal
- User-centric
- Accessibility-first
- Mobile-responsive

---

## Color Palette

### Primary Colors
- **Primary:** \`#3B82F6\` (Blue) - Trust, professionalism
- **Primary Dark:** \`#2563EB\` - Hover states
- **Primary Light:** \`#DBEAFE\` - Backgrounds

### Secondary Colors
- **Secondary:** \`#10B981\` (Green) - Success, positive actions
- **Accent:** \`#F59E0B\` (Orange) - Call-to-action, highlights

### Neutral Colors
- **Background:** \`#FFFFFF\` (White)
- **Surface:** \`#F9FAFB\` (Light gray)
- **Border:** \`#E5E7EB\` (Gray 200)
- **Text Primary:** \`#111827\` (Gray 900)
- **Text Secondary:** \`#6B7280\` (Gray 500)
- **Text Muted:** \`#9CA3AF\` (Gray 400)

### Status Colors
- **Success:** \`#10B981\` (Green)
- **Warning:** \`#F59E0B\` (Orange)
- **Error:** \`#EF4444\` (Red)
- **Info:** \`#3B82F6\` (Blue)

---

## Typography

### Font Families
- **Sans-serif:** Inter (primary)
- **Monospace:** JetBrains Mono (code)

### Type Scale
- **Display:** 48px / 3rem - Hero headings
- **H1:** 36px / 2.25rem - Page titles
- **H2:** 30px / 1.875rem - Section headings
- **H3:** 24px / 1.5rem - Subsection headings
- **H4:** 20px / 1.25rem - Card titles
- **Body Large:** 18px / 1.125rem - Prominent text
- **Body:** 16px / 1rem - Default text
- **Body Small:** 14px / 0.875rem - Secondary text
- **Caption:** 12px / 0.75rem - Captions, labels

### Font Weights
- **Regular:** 400 - Body text
- **Medium:** 500 - Emphasis
- **Semibold:** 600 - Subheadings
- **Bold:** 700 - Headings

---

## Spacing Scale

Use consistent spacing based on 4px grid:

- **xs:** 4px (0.25rem)
- **sm:** 8px (0.5rem)
- **md:** 16px (1rem)
- **lg:** 24px (1.5rem)
- **xl:** 32px (2rem)
- **2xl:** 48px (3rem)
- **3xl:** 64px (4rem)

---

## Border Radius

- **sm:** 4px - Small elements (badges, chips)
- **md:** 8px - Buttons, inputs
- **lg:** 12px - Cards, containers
- **xl:** 16px - Modals, panels
- **full:** 9999px - Pills, circular

---

## Shadows

- **sm:** \`0 1px 2px 0 rgb(0 0 0 / 0.05)\` - Subtle elevation
- **md:** \`0 4px 6px -1px rgb(0 0 0 / 0.1)\` - Cards
- **lg:** \`0 10px 15px -3px rgb(0 0 0 / 0.1)\` - Dropdowns
- **xl:** \`0 20px 25px -5px rgb(0 0 0 / 0.1)\` - Modals

---

## Component Patterns

### Buttons
\`\`\`tsx
// Primary button
<button className="bg-primary hover:bg-primary-dark text-white font-medium px-4 py-2 rounded-md transition-colors">
  Button Text
</button>

// Secondary button
<button className="bg-surface hover:bg-gray-200 text-gray-900 font-medium px-4 py-2 rounded-md border border-border transition-colors">
  Button Text
</button>
\`\`\`

### Cards
\`\`\`tsx
<div className="bg-white rounded-lg border border-border p-6 shadow-md hover:shadow-lg transition-shadow">
  <h3 className="text-xl font-semibold text-gray-900 mb-2">Card Title</h3>
  <p className="text-gray-600">Card content</p>
</div>
\`\`\`

### Forms
\`\`\`tsx
<div className="space-y-2">
  <label className="text-sm font-medium text-gray-700">Label</label>
  <input
    type="text"
    className="w-full px-3 py-2 border border-border rounded-md focus:ring-2 focus:ring-primary focus:border-primary"
  />
</div>
\`\`\`

### Navigation
- **Style:** Top bar, sticky positioning
- **Background:** White with subtle border
- **Hover states:** Light gray background
- **Active:** Primary color indicator

---

## Animation Guidelines

### Transitions
- **Duration:** 150-300ms for UI feedback
- **Easing:** ease-out for natural feel
- **Properties:** opacity, transform, colors

### Use Framer Motion for:
- Page transitions
- Modal enter/exit
- List animations
- Hover effects

\`\`\`tsx
import { motion } from 'framer-motion'

<motion.div
  initial={{ opacity: 0, y: 20 }}
  animate={{ opacity: 1, y: 0 }}
  transition={{ duration: 0.3 }}
>
  Content
</motion.div>
\`\`\`

---

## Responsive Breakpoints

- **sm:** 640px - Mobile landscape
- **md:** 768px - Tablet
- **lg:** 1024px - Desktop
- **xl:** 1280px - Large desktop

**Mobile-first approach:** Design for mobile, enhance for desktop

---

## Accessibility

- **Color Contrast:** WCAG AA minimum (4.5:1 for text)
- **Focus States:** Visible focus rings on interactive elements
- **ARIA Labels:** All interactive elements
- **Keyboard Navigation:** Full keyboard support
- **Screen Readers:** Semantic HTML

---

## Reference Applications

**Inspiration (UI Quality):**
- Linear - Clean, minimal, excellent micro-interactions
- Stripe - Professional, trustworthy, clear information hierarchy
- Vercel - Modern, fast, developer-focused

**Match this quality level in all implementations**

---

## Tailwind CSS Usage

### DO:
✅ Use design tokens: \`bg-primary\`, \`text-gray-900\`
✅ Use spacing scale: \`p-4\`, \`mb-6\`
✅ Mobile-first: \`className="text-sm md:text-base"\`
✅ Transitions: \`transition-colors duration-200\`

### DON'T:
❌ Hardcoded colors: \`bg-[#3B82F6]\`
❌ Arbitrary values: \`p-[13px]\`
❌ Inline styles: \`style={{ color: 'blue' }}\`

---

*Use this design system for ALL components and pages*
*Consistency is key to professional appearance*
`;
  }
}

export const designSystemGeneratorV2 = new DesignSystemGeneratorV2();
