/**
 * Handoff Generator
 * Creates handoff documents when builds are paused or interrupted
 */

import fs from 'fs/promises';
import path from 'path';

export interface HandoffData {
  projectId: string;
  projectName: string;
  projectPath: string;
  timestamp: string;
  buildPhase: string;
  currentTask?: {
    id: string;
    description: string;
    status: string;
  };
  completedTasks: number;
  totalTasks: number;
  recentActivity: Array<{
    timestamp: string;
    type: string;
    description: string;
  }>;
  filesCreated: string[];
  filesModified: string[];
  pendingTasks: Array<{
    id: string;
    description: string;
    dependencies: string[];
  }>;
  context: {
    prdSummary: string;
    designSystemApplied: boolean;
    componentsUsed: string[];
  };
  nextSteps: string[];
  blockers?: Array<{
    description: string;
    severity: 'low' | 'medium' | 'high';
  }>;
}

export class HandoffGenerator {

  /**
   * Generate comprehensive handoff document
   */
  async generate(data: HandoffData): Promise<string> {
    const handoffDoc = `# Build Handoff - ${data.projectName}

*Generated: ${new Date(data.timestamp).toLocaleString()}*
*Project ID: ${data.projectId}*

---

## Current Status

**Build Phase:** ${data.buildPhase}
**Progress:** ${data.completedTasks}/${data.totalTasks} tasks completed (${Math.round((data.completedTasks / data.totalTasks) * 100)}%)

${data.currentTask ? `**Current Task:** ${data.currentTask.description} (${data.currentTask.status})` : '**Current Task:** None - awaiting next task'}

---

## Project Context

**Project Path:** \`${data.projectPath}\`

**PRD Summary:**
${data.context.prdSummary}

**Design System Applied:** ${data.context.designSystemApplied ? '✅ Yes' : '❌ No'}

**Components Used:**
${data.context.componentsUsed.length > 0 ? data.context.componentsUsed.map(c => `- ${c}`).join('\n') : '- None yet'}

---

## Recent Activity

${data.recentActivity.slice(0, 10).map(activity =>
  `**${new Date(activity.timestamp).toLocaleTimeString()}** - ${activity.type}: ${activity.description}`
).join('\n')}

---

## Files Modified

### Created (${data.filesCreated.length} files)
${data.filesCreated.slice(0, 20).map(f => `- ${f}`).join('\n')}
${data.filesCreated.length > 20 ? `\n... and ${data.filesCreated.length - 20} more` : ''}

### Modified (${data.filesModified.length} files)
${data.filesModified.slice(0, 20).map(f => `- ${f}`).join('\n')}
${data.filesModified.length > 20 ? `\n... and ${data.filesModified.length - 20} more` : ''}

---

## Pending Tasks

${data.pendingTasks.slice(0, 10).map((task, idx) => `
### ${idx + 1}. ${task.description}
**ID:** ${task.id}
${task.dependencies.length > 0 ? `**Dependencies:** ${task.dependencies.join(', ')}` : '**Dependencies:** None'}
`).join('\n')}

${data.pendingTasks.length > 10 ? `\n... and ${data.pendingTasks.length - 10} more tasks` : ''}

---

## Next Steps

${data.nextSteps.map((step, idx) => `${idx + 1}. ${step}`).join('\n')}

---

${data.blockers && data.blockers.length > 0 ? `## Blockers

${data.blockers.map(blocker => `
- **[${blocker.severity.toUpperCase()}]** ${blocker.description}
`).join('\n')}

---
` : ''}

## Resuming This Build

When resuming this build, Claude should:

1. **Read this handoff document** to understand current state
2. **Load BUILD_STATE.json** for complete file manifest and task list
3. **Review DESIGN_SYSTEM.md** and COMPONENT_CATALOG.md for consistency
4. **Check git status** to see uncommitted changes
5. **Continue with next pending task** (Task ID: ${data.pendingTasks[0]?.id || 'TBD'})

**Critical Files:**
- \`.buildrunner/BUILD_DOC.md\` - Project overview and requirements
- \`.buildrunner/BUILD_STATE.json\` - Complete build state
- \`.buildrunner/TASKS.md\` - Full task list with dependencies
- \`.buildrunner/DESIGN_SYSTEM.md\` - Design system to maintain consistency
- \`.buildrunner/BUILD_LOG.md\` - Detailed activity log

---

## Quality Standards

Maintain the same quality standards established in this build:
- **UI Quality:** Linear/Stripe level polish
- **Code Quality:** TypeScript strict mode, ESLint passing
- **Design System:** Consistently applied from DESIGN_SYSTEM.md
- **Components:** Use shadcn/ui + custom components from catalog
- **Git Commits:** Semantic commits per task
- **Testing:** All features tested, no regressions

---

*This handoff was automatically generated by BuildRunner*
*For questions, review .buildrunner/ directory for complete context*
`;

    return handoffDoc;
  }

  /**
   * Save handoff document
   */
  async save(data: HandoffData): Promise<void> {
    const handoffDoc = await this.generate(data);
    const buildRunnerDir = path.join(data.projectPath, '.buildrunner');

    // Save main handoff
    await fs.writeFile(
      path.join(buildRunnerDir, 'HANDOFF.md'),
      handoffDoc
    );

    // Save timestamped snapshot
    const timestamp = new Date().toISOString().replace(/:/g, '-').split('.')[0];
    const snapshotDir = path.join(buildRunnerDir, 'handoffs');
    await fs.mkdir(snapshotDir, { recursive: true });

    await fs.writeFile(
      path.join(snapshotDir, `handoff-${timestamp}.md`),
      handoffDoc
    );
  }

  /**
   * Extract handoff data from build state
   */
  async extractFromBuildState(projectPath: string): Promise<HandoffData | null> {
    try {
      const buildStatePath = path.join(projectPath, '.buildrunner', 'BUILD_STATE.json');
      const buildStateContent = await fs.readFile(buildStatePath, 'utf-8');
      const buildState = JSON.parse(buildStateContent);

      // Load additional context
      const prdPath = path.join(projectPath, '.buildrunner', 'BUILD_DOC.md');
      let prdSummary = 'No PRD available';
      try {
        const prdContent = await fs.readFile(prdPath, 'utf-8');
        // Extract first paragraph as summary
        const match = prdContent.match(/##\s*Project Overview\s*\n\n(.*?)\n\n/s);
        prdSummary = match ? match[1].trim() : prdContent.slice(0, 500);
      } catch {
        // PRD not available
      }

      return {
        projectId: buildState.projectId,
        projectName: buildState.projectName || path.basename(projectPath),
        projectPath,
        timestamp: new Date().toISOString(),
        buildPhase: buildState.buildPhase || 'in_progress',
        currentTask: buildState.currentTask,
        completedTasks: buildState.completedTasks || 0,
        totalTasks: buildState.totalTasks || 0,
        recentActivity: buildState.activityLog?.slice(-20) || [],
        filesCreated: buildState.fileManifest?.filter((f: any) => f.status === 'created').map((f: any) => f.path) || [],
        filesModified: buildState.fileManifest?.filter((f: any) => f.status === 'modified').map((f: any) => f.path) || [],
        pendingTasks: buildState.tasks?.filter((t: any) => t.status === 'pending' || t.status === 'blocked') || [],
        context: {
          prdSummary,
          designSystemApplied: buildState.designSystemApplied || false,
          componentsUsed: buildState.artifacts?.components || []
        },
        nextSteps: this.generateNextSteps(buildState),
        blockers: buildState.blockers || []
      };
    } catch (error) {
      console.error('Failed to extract handoff data:', error);
      return null;
    }
  }

  /**
   * Generate next steps from build state
   */
  private generateNextSteps(buildState: any): string[] {
    const steps: string[] = [];

    if (buildState.currentTask) {
      steps.push(`Resume ${buildState.currentTask.description}`);
    } else if (buildState.tasks) {
      const nextTask = buildState.tasks.find((t: any) =>
        t.status === 'pending' &&
        (!t.dependencies || t.dependencies.length === 0 ||
         t.dependencies.every((dep: string) =>
           buildState.tasks.find((dt: any) => dt.id === dep)?.status === 'completed'
         ))
      );

      if (nextTask) {
        steps.push(`Start next task: ${nextTask.description}`);
      }
    }

    if (buildState.blockers && buildState.blockers.length > 0) {
      steps.push('Resolve blockers before continuing');
    }

    if (steps.length === 0) {
      steps.push('Review BUILD_STATE.json to determine next action');
    }

    return steps;
  }
}

export const handoffGenerator = new HandoffGenerator();
