'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

interface Technology {
  name: string;
  category: 'frontend' | 'backend' | 'database' | 'infrastructure' | 'service';
  reasoning: string;
  difficulty: 'easy' | 'medium' | 'advanced';
  setupRequired: boolean;
  status?: 'already_setup' | 'standard_tool' | 'likely_installed' | 'needs_account';
  statusNote?: string;
  setupGuideUrl?: string;
  signupUrl?: string;
  canIntegrateInApp?: boolean;
}

interface Microstep {
  id: string;
  title: string;
  description: string;
  estimatedHours: number;
  dependencies: string[];
  status: 'pending' | 'in_progress' | 'completed';
}

interface Step {
  id: string;
  title: string;
  description: string;
  estimatedDays: number;
  microsteps: Microstep[];
  dependencies: string[];
  status: 'pending' | 'in_progress' | 'completed';
}

interface Milestone {
  id: string;
  title: string;
  description: string;
  estimatedWeeks: number;
  steps: Step[];
  dependencies: string[];
  status: 'pending' | 'in_progress' | 'completed';
}

interface Architecture {
  recommendedStack: string;
  technologies: Technology[];
}

interface ProjectPlan {
  architecture?: Architecture;
  milestones: Milestone[];
  totalEstimatedWeeks: number;
  generatedAt: string;
}

interface BuildMetadata {
  buildId: string;
  timestamp: string;
  componentCount: number;
  fileCount: number;
  status: 'completed' | 'failed' | 'partial';
  buildDirectory: string;
  duration?: number;
}

interface Project {
  id: string;
  name: string;
  ref?: string;
  url?: string;
  status: 'active' | 'inactive' | 'completed' | 'archived';
  created_at: string;
  updated_at?: string;
  plan?: ProjectPlan;
  builds?: BuildMetadata[];
  currentPhase?: 'prd' | 'plan' | 'build' | 'complete';
  lastBuildId?: string; // Auto-load this on project open
  phaseProgress?: {
    prd: boolean;
    plan: boolean;
    build: boolean;
  };
}

interface ProjectContextType {
  currentProject: Project | null;
  projects: Project[];
  setCurrentProject: (project: Project) => void;
  loading: boolean;
  loadPlan: () => Promise<void>;
}

// Export types for use in other components
export type { Project, ProjectPlan, Milestone, Step, Microstep, Technology, Architecture, BuildMetadata };

const ProjectContext = createContext<ProjectContextType | undefined>(undefined);

export function ProjectProvider({ children }: { children: React.ReactNode }) {
  const [currentProject, setCurrentProject] = useState<Project | null>(null);
  const [projects, setProjects] = useState<Project[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Load projects from localStorage or API
    const loadProjects = async () => {
      try {
        // For demo, use mock data
        const mockProjects: Project[] = [
          {
            id: '1',
            name: 'BuildRunner SaaS',
            ref: 'buildrunner-main',
            url: 'https://buildrunner-main.supabase.co',
            status: 'active',
            created_at: new Date().toISOString(),
          },
          {
            id: '2',
            name: 'Demo Project',
            status: 'inactive',
            created_at: new Date().toISOString(),
          },
        ];

        setProjects(mockProjects);
        
        // Set current project from localStorage or default to first
        const savedProjectId = localStorage.getItem('currentProjectId');
        const savedProject = mockProjects.find(p => p.id === savedProjectId);
        setCurrentProject(savedProject || mockProjects[0]);
      } catch (error) {
        console.error('Failed to load projects:', error);
      } finally {
        setLoading(false);
      }
    };

    loadProjects();
  }, []);

  const handleSetCurrentProject = (project: Project) => {
    setCurrentProject(project);
    localStorage.setItem('currentProjectId', project.id);
  };

  const loadPlan = async () => {
    if (!currentProject) return;

    try {
      // Load plan from localStorage (generated by plan page)
      const savedPlanKey = `buildrunner_plan_${currentProject.id}`;
      const savedPlan = localStorage.getItem(savedPlanKey);

      if (savedPlan) {
        const plan: ProjectPlan = JSON.parse(savedPlan);
        setCurrentProject({
          ...currentProject,
          plan,
        });
      } else {
        console.log('No saved plan found for project:', currentProject.id);
      }
    } catch (error) {
      console.error('Failed to load plan:', error);
    }
  };

  return (
    <ProjectContext.Provider value={{
      currentProject,
      projects,
      setCurrentProject: handleSetCurrentProject,
      loading,
      loadPlan,
    }}>
      {children}
    </ProjectContext.Provider>
  );
}

export function useProject() {
  const context = useContext(ProjectContext);
  if (context === undefined) {
    throw new Error('useProject must be used within a ProjectProvider');
  }
  return context;
}
