import fs from 'fs/promises';
import path from 'path';
import { exec } from 'child_process';
import { promisify } from 'util';
import os from 'os';

const execAsync = promisify(exec);

export interface ProjectInitConfig {
  projectId: string;
  projectName: string;
  description?: string;
  techStack?: {
    framework: string;
    version: string;
    styling: string;
    componentLibrary: string;
  };
}

/**
 * Initializes a new project in ~/Projects/ directory
 */
export class ProjectInitializer {

  /**
   * Initialize a new project with complete structure
   */
  async initialize(config: ProjectInitConfig): Promise<{
    success: boolean;
    projectPath: string;
    error?: Error;
  }> {
    try {
      const homeDir = os.homedir();
      const projectsDir = path.join(homeDir, 'Projects');
      const projectPath = path.join(projectsDir, config.projectName);

      // Ensure Projects directory exists
      await fs.mkdir(projectsDir, { recursive: true });

      // Check if project already exists
      try {
        await fs.access(projectPath);
        throw new Error(`Project ${config.projectName} already exists at ${projectPath}`);
      } catch {
        // Good, project doesn't exist
      }

      // Create project directory
      await fs.mkdir(projectPath, { recursive: true });

      // Create .buildrunner directory
      await this.createBuildRunnerStructure(projectPath);

      // Initialize Next.js project
      await this.initializeNextJs(projectPath, config);

      // Initialize git repository
      await this.initializeGit(projectPath, config);

      // Create initial build documents
      await this.createInitialDocs(projectPath, config);

      return {
        success: true,
        projectPath
      };

    } catch (error) {
      return {
        success: false,
        projectPath: '',
        error: error as Error
      };
    }
  }

  /**
   * Create .buildrunner directory structure
   */
  private async createBuildRunnerStructure(projectPath: string): Promise<void> {
    const buildRunnerDir = path.join(projectPath, '.buildrunner');

    // Create directories
    await fs.mkdir(buildRunnerDir, { recursive: true });
    await fs.mkdir(path.join(buildRunnerDir, 'handoffs'), { recursive: true });
    await fs.mkdir(path.join(buildRunnerDir, 'snapshots'), { recursive: true });

    // Create placeholder files
    const files = [
      'BUILD_DOC.md',
      'BUILD_STATE.json',
      'TASKS.md',
      'HANDOFF.md',
      'DESIGN_SYSTEM.md',
      'COMPONENT_CATALOG.md',
      'BUILD_LOG.md',
      'GAP_ANALYSIS.md'
    ];

    for (const file of files) {
      const filePath = path.join(buildRunnerDir, file);
      await fs.writeFile(filePath, `# ${file.replace('.md', '').replace('_', ' ')}\n\n*Generated by BuildRunner*\n`);
    }

    // Initialize BUILD_STATE.json
    const buildState = {
      projectId: '',
      projectPath,
      currentTask: null,
      fileManifest: [],
      dependencies: {},
      artifacts: {
        components: [],
        apis: [],
        pages: []
      },
      lastActivity: new Date().toISOString(),
      buildPhase: 'initialized',
      completedTasks: 0,
      totalTasks: 0
    };

    await fs.writeFile(
      path.join(buildRunnerDir, 'BUILD_STATE.json'),
      JSON.stringify(buildState, null, 2)
    );
  }

  /**
   * Initialize Next.js project
   */
  private async initializeNextJs(projectPath: string, config: ProjectInitConfig): Promise<void> {
    // Create package.json
    const packageJson = {
      name: config.projectName.toLowerCase().replace(/\s+/g, '-'),
      version: '1.0.0',
      private: true,
      scripts: {
        dev: 'next dev',
        build: 'next build',
        start: 'next start',
        lint: 'next lint'
      },
      dependencies: {
        'react': '^18.2.0',
        'react-dom': '^18.2.0',
        'next': '^14.2.0',
        'tailwindcss': '^4.0.0',
        'typescript': '^5.3.0',
        '@types/react': '^18.2.0',
        '@types/node': '^20.0.0',
        'framer-motion': '^11.0.0'
      },
      devDependencies: {
        '@types/react-dom': '^18.2.0',
        'eslint': '^8.0.0',
        'eslint-config-next': '14.2.0'
      }
    };

    await fs.writeFile(
      path.join(projectPath, 'package.json'),
      JSON.stringify(packageJson, null, 2)
    );

    // Create tsconfig.json
    const tsConfig = {
      compilerOptions: {
        target: 'ES2017',
        lib: ['dom', 'dom.iterable', 'esnext'],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: 'esnext',
        moduleResolution: 'bundler',
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: 'preserve',
        incremental: true,
        plugins: [{ name: 'next' }],
        paths: {
          '@/*': ['./src/*']
        }
      },
      include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
      exclude: ['node_modules']
    };

    await fs.writeFile(
      path.join(projectPath, 'tsconfig.json'),
      JSON.stringify(tsConfig, null, 2)
    );

    // Create basic directory structure
    await fs.mkdir(path.join(projectPath, 'src'), { recursive: true });
    await fs.mkdir(path.join(projectPath, 'src', 'app'), { recursive: true });
    await fs.mkdir(path.join(projectPath, 'src', 'components'), { recursive: true });
    await fs.mkdir(path.join(projectPath, 'src', 'lib'), { recursive: true });
    await fs.mkdir(path.join(projectPath, 'public'), { recursive: true });

    // Create minimal app layout
    const layoutContent = `export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
`;

    await fs.writeFile(path.join(projectPath, 'src', 'app', 'layout.tsx'), layoutContent);

    // Create placeholder page
    const pageContent = `export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-24">
      <h1 className="text-4xl font-bold">Welcome to ${config.projectName}</h1>
      <p className="text-gray-600 mt-4">Generated by BuildRunner + Claude CLI</p>
    </main>
  )
}
`;

    await fs.writeFile(path.join(projectPath, 'src', 'app', 'page.tsx'), pageContent);

    // Create tailwind.config.ts
    const tailwindConfig = `import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
export default config
`;

    await fs.writeFile(path.join(projectPath, 'tailwind.config.ts'), tailwindConfig);

    // Create .gitignore
    const gitignore = `# dependencies
/node_modules
/.pnp
.pnp.js

# testing
/coverage

# next.js
/.next/
/out/

# production
/build

# misc
.DS_Store
*.pem

# debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# local env files
.env*.local

# vercel
.vercel

# typescript
*.tsbuildinfo
next-env.d.ts

# buildrunner snapshots
.buildrunner/snapshots/
`;

    await fs.writeFile(path.join(projectPath, '.gitignore'), gitignore);
  }

  /**
   * Initialize git repository
   */
  private async initializeGit(projectPath: string, config: ProjectInitConfig): Promise<void> {
    try {
      // Initialize git
      await execAsync('git init', { cwd: projectPath });

      // Initial commit
      await execAsync('git add .', { cwd: projectPath });
      await execAsync(
        `git commit -m "chore: Initialize ${config.projectName} from BuildRunner"`,
        { cwd: projectPath }
      );

      // Try to create GitHub repo (will fail gracefully if gh CLI not available)
      try {
        const repoName = config.projectName.replace(/\s+/g, '-');
        await execAsync(
          `gh repo create ${repoName} --private --source=. --remote=origin`,
          { cwd: projectPath }
        );
      } catch {
        // GitHub CLI not available or not authenticated - skip
      }

    } catch (error) {
      // Git initialization failed - non-critical
      console.warn('Git initialization skipped:', error);
    }
  }

  /**
   * Create initial documentation
   */
  private async createInitialDocs(projectPath: string, config: ProjectInitConfig): Promise<void> {
    const buildRunnerDir = path.join(projectPath, '.buildrunner');

    // README.md
    const readme = `# ${config.projectName}

${config.description || 'A modern web application built with Next.js and Claude CLI'}

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000) with your browser.

## Tech Stack

- **Framework:** Next.js 14 (App Router)
- **Styling:** Tailwind CSS 4
- **Language:** TypeScript
- **Animations:** Framer Motion

## Build System

This project was built using BuildRunner with Claude CLI integration.

Build metadata is tracked in \`.buildrunner/\` directory.

---

*Generated by BuildRunner + Claude CLI*
`;

    await fs.writeFile(path.join(projectPath, 'README.md'), readme);
  }

  /**
   * Check if project exists
   */
  async projectExists(projectName: string): Promise<boolean> {
    try {
      const homeDir = os.homedir();
      const projectPath = path.join(homeDir, 'Projects', projectName);
      await fs.access(projectPath);
      return true;
    } catch {
      return false;
    }
  }

  /**
   * Get project path
   */
  getProjectPath(projectName: string): string {
    const homeDir = os.homedir();
    return path.join(homeDir, 'Projects', projectName);
  }
}

export const projectInitializer = new ProjectInitializer();
