# BuildRunner Governance Policy
# This file defines the governance rules and safety controls for the project

version: "1.0.0"
project_id: "buildrunner-saas"
updated_at: "2025-10-30T23:30:00.000Z"
updated_by: "system"

# Protected paths that require special approval
protected_paths:
  - "/buildrunner/specs/plan.json"
  - "/buildrunner/state/runner_state.json"
  - "/supabase/migrations/"
  - "/apps/server/lib/vault.ts"
  - "/.github/workflows/"
  - "/governance/policy.yml"
  - "/package.json"
  - "/package-lock.json"

# Approval requirements
approvals:
  required:
    - role: "admin"
      count: 1
    - role: "tech_lead" 
      count: 1
  protected_paths_override:
    "/buildrunner/specs/plan.json":
      - role: "product_owner"
        count: 1
      - role: "tech_lead"
        count: 1
    "/supabase/migrations/":
      - role: "database_admin"
        count: 1
      - role: "tech_lead"
        count: 1

# Pull Request requirements
pr_requirements:
  microstep_id: true
  microstep_id_pattern: "^p\\d+\\.s\\d+\\.ms\\d+:"
  checklists:
    - "AC checklist present"
    - "Testing completed"
    - "Documentation updated"
  title_pattern: "^(p\\d+\\.s\\d+\\.ms\\d+:|feat|fix|docs|refactor|test):"
  description_min_length: 50

# Secret scanning configuration
secret_scan:
  enabled: true
  block_on_detection: true
  deny_patterns:
    - "(?i)api[_-]?key\\s*[=:]\\s*['\"]?[a-zA-Z0-9]{20,}['\"]?"
    - "(?i)secret[_-]?key\\s*[=:]\\s*['\"]?[a-zA-Z0-9]{20,}['\"]?"
    - "(?i)password\\s*[=:]\\s*['\"]?[a-zA-Z0-9]{8,}['\"]?"
    - "AKIA[0-9A-Z]{16}"  # AWS Access Key
    - "sk-[a-zA-Z0-9]{48}"  # OpenAI API Key
    - "xoxb-[0-9]{11}-[0-9]{11}-[a-zA-Z0-9]{24}"  # Slack Bot Token
    - "ghp_[a-zA-Z0-9]{36}"  # GitHub Personal Access Token
    - "gho_[a-zA-Z0-9]{36}"  # GitHub OAuth Token
    - "postgres://[^\\s]+"  # Database URLs
    - "mongodb://[^\\s]+"
    - "redis://[^\\s]+"
  allowed_patterns:
    - "example_api_key"
    - "your_api_key_here"
    - "placeholder_secret"
    - "\\[REDACTED\\]"
    - "\\*\\*\\*\\*\\*"
  exclude_files:
    - "*.md"
    - "*.example"
    - "*.template"
    - "governance/policy.yml"

# Risk management
risk:
  require_rollback: true
  require_post_check: true
  risk_levels:
    low:
      require_rollback: false
      require_post_check: false
      auto_merge_allowed: true
    medium:
      require_rollback: true
      require_post_check: false
      auto_merge_allowed: false
    high:
      require_rollback: true
      require_post_check: true
      auto_merge_allowed: false
      additional_approvals: 1
    critical:
      require_rollback: true
      require_post_check: true
      auto_merge_allowed: false
      additional_approvals: 2
      require_staging_test: true

# Microstep enforcement
microsteps:
  enforce_in_commits: true
  enforce_in_pr_title: true
  enforce_in_pr_description: true
  require_acceptance_criteria: true
  require_testing_evidence: true
  blocked_statuses:
    - "blocked"
    - "on_hold"
  allowed_transitions:
    "todo": ["doing", "blocked"]
    "doing": ["done", "blocked", "todo"]
    "blocked": ["todo", "doing"]
    "done": []  # Final state

# Branch protection
branches:
  main:
    require_pr: true
    require_reviews: 2
    dismiss_stale_reviews: true
    require_code_owner_reviews: true
    require_status_checks: true
    required_status_checks:
      - "BuildRunner QA"
      - "Governance: Protected Paths"
      - "Governance: Secrets Scan"
      - "Governance: Microstep ID"
    restrict_pushes: true
    allowed_push_users: []
  develop:
    require_pr: true
    require_reviews: 1
    require_status_checks: true
    required_status_checks:
      - "BuildRunner QA"
      - "Governance: Secrets Scan"

# Notifications
notifications:
  slack:
    enabled: false
    webhook_url: ""
    channels:
      governance_alerts: "#governance"
      security_alerts: "#security"
  email:
    enabled: true
    recipients:
      - "admin@dockeryai.com"
  github:
    enabled: true
    create_issues: true
    assign_to_author: true

# Audit settings
audit:
  log_all_actions: true
  retention_days: 365
  export_format: "json"
  include_sensitive_data: false
  
# Emergency procedures
emergency:
  bypass_enabled: true
  bypass_roles:
    - "admin"
    - "emergency_contact"
  bypass_requires_justification: true
  bypass_requires_post_review: true
  bypass_notification_required: true

# Integration settings
integrations:
  github:
    enabled: true
    check_runs: true
    commit_status: true
    pr_comments: true
  supabase:
    enabled: true
    log_to_runner_events: true
  monitoring:
    enabled: true
    alert_on_violations: true

  # External integrations allowed
  integrations_allowed:
    - jira
    - linear
    - vercel
    - render
    - netlify
    - github
    - slack
  external_sync_required: true
  require_preview_for_phase:
    - QA
    - Beta
  max_integrations_per_project: 10

  # Preview environment requirements
  preview_environments:
    required_for_phases:
      - QA
      - Beta
    providers_allowed:
      - vercel
      - render
      - netlify
    auto_deploy_branches:
      - main
      - develop
      - "feature/*"
    retention_days: 7

# Design System Governance
design_system:
  design_parity_required: true
  design_token_threshold: 95
  figma_project_id: "${FIGMA_PROJECT_ID}"
  figma_file_id: "${FIGMA_FILE_ID}"

  visual_regression:
    similarity_threshold: 0.95
    pixel_diff_threshold: 100
    enabled_for_branches:
      - main
      - develop
      - "release/*"

  component_parity:
    enforce_figma_mapping: true
    require_component_docs: true
    allowed_drift_percentage: 5

  token_sync:
    auto_sync_enabled: false
    require_manual_approval: true
    sync_schedule: "0 9 * * 1" # Monday 9 AM

  notifications:
    design_drift_alerts: true
    token_update_notifications: true
    visual_regression_failures: true

# Internationalization & Accessibility Governance
i18n:
  required: true
  default_locale: "en"
  supported_locales:
    - "en"
    - "es"
    - "fr"
    - "de"
  fallback_locale: "en"

  translation_coverage:
    minimum_percentage: 90
    enforce_on_build: true
    exclude_namespaces:
      - "dev"
      - "test"

  ai_translation:
    enabled: true
    auto_translate_threshold: 80
    require_human_verification: true
    max_batch_size: 100

  governance_sync:
    untranslated_warning_threshold: 10
    block_deployment_on_missing: false
    notify_translators: true

accessibility:
  required: true
  wcag_level: "AA"
  wcag_version: "2.1"

  audit_requirements:
    lighthouse_score_min: 90
    axe_violations_max: 0
    color_contrast_min: 4.5
    keyboard_navigation_required: true

  automated_testing:
    enabled: true
    run_on_pr: true
    fail_on_violations: true
    include_pages:
      - "/"
      - "/dashboard"
      - "/projects"
      - "/settings"
      - "/admin"

  manual_testing:
    required_for_major_releases: true
    screen_reader_testing: true
    keyboard_only_testing: true
    high_contrast_testing: true

  reporting:
    store_audit_results: true
    generate_compliance_report: true
    notify_on_regression: true

# Offline & Resilience Governance
offline_resilience:
  offline_mode_enabled: true

  # Sync queue configuration
  sync_queue:
    max_queue_size: 1000
    max_age_hours: 72
    batch_size: 10

  # Exponential backoff configuration
  sync_backoff:
    min_ms: 500
    max_ms: 30000
    factor: 2
    jitter: true
    max_attempts: 5

  # Circuit breaker configuration
  circuit_breaker:
    failure_threshold: 5
    success_threshold: 3
    cooldown_ms: 60000
    half_open_max_calls: 3

  # Conflict resolution strategy
  conflict_resolution:
    strategy: "prompt"           # "prompt", "local_wins", "remote_wins", "auto_merge"
    auto_if_trivial: true
    require_human_verification: true
    max_auto_resolve_fields: 10

  # Degraded mode configuration
  degraded_mode:
    allowed: true
    auto_enable_threshold: 3     # consecutive failures
    features_disabled:
      - "real_time_sync"
      - "external_integrations"
      - "ai_operations"
    features_enabled:
      - "local_editing"
      - "plan_browsing"
      - "export_operations"

  # Health monitoring
  health_monitoring:
    enabled: true
    probe_interval_ms: 30000
    timeout_ms: 10000
    targets:
      - "supabase_db"
      - "supabase_edge"
      - "openai_api"
      - "github_api"
      - "figma_api"
    alert_thresholds:
      consecutive_failures: 3
      latency_ms: 5000
      error_rate_percent: 10

  # Failover configuration
  failover:
    enabled: true
    read_only_fallback: true
    cache_ttl_ms: 300000         # 5 minutes
    fallback_endpoints:
      supabase_db: "read_replica_url"
      static_assets: "cdn_fallback_url"

  # Queue visibility and alerts
  queue_management:
    dashboard_enabled: true
    real_time_updates: true
    alert_on_backlog_size: 100
    alert_on_age_hours: 24
    alert_channels:
      - "slack"
      - "email"
      - "webhook"

  # Chaos engineering
  chaos_testing:
    enabled: true
    environments: ["development", "staging"]
    max_failure_duration_ms: 60000
    failure_types:
      - "network_latency"
      - "network_drop"
      - "server_error"
      - "timeout"
    schedule: "nightly"

# Public Launch & Marketplace Governance
public_launch:
  # Public signup configuration
  public_signup_enabled: true
  signup_approval_required: false
  email_verification_required: true

  # Account limits for free tier
  max_free_projects: 3
  max_free_team_members: 5
  max_free_storage_mb: 1000

  # Onboarding requirements
  onboarding_required: true
  onboarding_steps:
    - "welcome"
    - "role_selection"
    - "goals_setup"
    - "template_selection"
    - "first_project"
    - "billing_setup"

  # Marketplace moderation
  marketplace:
    enabled: true
    auto_publish: false
    moderation_required: true
    verification_required_for_featured: true

    # Content policies
    content_policies:
      max_title_length: 100
      max_description_length: 1000
      required_tags_min: 1
      required_tags_max: 10
      allowed_file_types: ["json", "ts", "tsx", "js", "jsx", "md", "yml", "yaml"]
      max_file_size_mb: 10

    # Review policies
    review_policies:
      min_rating: 1
      max_rating: 5
      require_comment_for_low_rating: true
      max_reviews_per_user_per_item: 1

    # Publishing requirements
    publishing_requirements:
      min_description_length: 50
      require_readme: true
      require_version: true
      require_tags: true

  # Growth and referrals
  referrals:
    enabled: true
    credits_per_referral: 100
    max_referrals_per_user: 50
    referral_code_length: 8
    referral_expiry_days: 365

  # Feedback and support
  feedback:
    enabled: true
    anonymous_feedback_allowed: true
    categories:
      - "bug_report"
      - "feature_request"
      - "user_experience"
      - "performance"
      - "documentation"
      - "billing"
      - "other"

    # NPS surveys
    nps_surveys:
      enabled: true
      frequency_days: 30
      min_usage_days: 7

  # Rate limiting for public endpoints
  rate_limits:
    signup_per_ip_per_hour: 5
    feedback_per_user_per_hour: 10
    marketplace_installs_per_user_per_hour: 50
    api_requests_per_user_per_minute: 100

  # Content moderation
  moderation:
    auto_flag_keywords:
      - "spam"
      - "scam"
      - "malware"
      - "virus"

    review_queue_enabled: true
    admin_approval_required_for:
      - "featured_items"
      - "verified_authors"
      - "high_install_items"

  # Launch metrics and telemetry
  telemetry:
    enabled: true
    anonymous_usage_tracking: true
    performance_monitoring: true
    error_tracking: true

    # Events to track
    tracked_events:
      - "user_signup"
      - "onboarding_completed"
      - "first_project_created"
      - "marketplace_item_installed"
      - "referral_used"
      - "feedback_submitted"
      - "subscription_started"

  # SEO and marketing
  seo:
    sitemap_enabled: true
    robots_txt_enabled: true
    structured_data_enabled: true
    open_graph_enabled: true

    # Analytics
    analytics:
      provider: "plausible"  # or "google_analytics"
      anonymous_tracking: true
      respect_dnt: true

# Continuous Evaluation & Auto-Optimization Governance
evals_optimization:
  # Evaluation requirements
  evals:
    required: true
    min_quality_score: 0.85
    min_pass_rate: 0.90
    schedule_cron: "0 2 * * *"  # Daily at 2 AM UTC

    # Quality gates
    quality_gates:
      pr_gate_enabled: true
      nightly_gate_enabled: true
      regression_threshold: 0.05  # 5% score drop triggers alert

    # Golden dataset requirements
    golden_datasets:
      min_items_per_set: 30
      max_items_per_set: 1000
      required_sets: ["planner_golden", "builder_golden", "qa_golden", "explain_golden"]

    # Scoring methods
    scoring:
      methods: ["exact_match", "bleu", "rouge", "rubric", "pass_at_k"]
      default_method: "rubric"
      rubric_criteria: ["correctness", "completeness", "clarity", "efficiency"]

  # Telemetry and monitoring
  telemetry:
    enabled: true
    pii_redaction: true
    retention_days: 90

    # Data collection
    collection:
      capture_inputs: true
      capture_outputs: true
      capture_errors: true
      capture_performance: true

    # Redaction rules
    redaction:
      email_addresses: true
      phone_numbers: true
      credit_cards: true
      ssn_numbers: true
      api_keys: true
      passwords: true
      custom_patterns: []

    # Sampling rates
    sampling:
      success_rate: 0.1    # 10% of successful requests
      error_rate: 1.0      # 100% of errors
      slow_request_rate: 1.0  # 100% of slow requests (>5s)

  # Safety and guardrails
  safety:
    enabled: true
    redteam_required: true
    max_severity_allowed: "medium"

    # Guardrail types
    guardrails:
      content_policy: true
      prompt_injection: true
      data_leakage: true
      bias_detection: true
      toxicity_detection: true

    # Safety scoring
    scoring:
      min_safety_score: 0.95
      severity_weights:
        low: 0.1
        medium: 0.5
        high: 1.0
        critical: 2.0

    # Red team testing
    redteam:
      frequency: "weekly"
      min_attempts_per_task: 100
      adversarial_prompts: true
      jailbreak_attempts: true
      bias_probes: true

    # Response policies
    response:
      auto_block_critical: true
      auto_escalate_high: true
      require_review_medium: true

  # Auto-optimization
  optimization:
    enabled: true
    algorithm: "thompson_sampling"  # or "epsilon_greedy", "ucb"

    # Budget constraints
    budget:
      max_cost_per_request_usd: 0.10
      max_latency_ms: 5000
      max_tokens_per_request: 4000

    # Optimization targets
    targets:
      primary: "quality_score"
      secondary: ["latency", "cost"]
      weights:
        quality: 0.6
        latency: 0.2
        cost: 0.2

    # Rollout strategy
    rollout:
      strategy: "canary"
      canary_percentage: 5
      ramp_up_duration_hours: 24
      success_threshold: 0.95

    # Rollback triggers
    rollback:
      auto_rollback_enabled: true
      quality_drop_threshold: 0.05
      error_rate_threshold: 0.10
      latency_increase_threshold: 2.0

  # Prompt management
  prompts:
    versioning: true
    a_b_testing: true
    max_variants_per_task: 5

    # Variant management
    variants:
      auto_generate: true
      generation_methods: ["paraphrase", "simplify", "elaborate", "format_change"]
      min_performance_samples: 100

    # Template requirements
    templates:
      require_description: true
      require_examples: true
      require_validation: true
      max_length_chars: 8000

  # Model management
  models:
    multi_model_routing: true
    fallback_enabled: true

    # Model selection
    selection:
      criteria: ["quality", "cost", "latency", "availability"]
      default_model: "gpt-4"
      fallback_model: "gpt-3.5-turbo"

    # Performance tracking
    tracking:
      track_per_task: true
      track_per_prompt: true
      update_frequency_hours: 1

  # Reporting and alerts
  reporting:
    daily_reports: true
    weekly_summaries: true
    regression_alerts: true

    # Alert channels
    alerts:
      slack_webhook: true
      email_notifications: true
      dashboard_notifications: true

    # Report recipients
    recipients:
      daily: ["engineering", "product"]
      weekly: ["leadership", "engineering", "product"]
      critical: ["on_call", "engineering_lead"]

  # Compliance and audit
  compliance:
    audit_trail: true
    data_retention: true
    privacy_compliance: true

    # Audit requirements
    audit:
      log_all_changes: true
      require_approval_for: ["prompt_changes", "model_changes", "policy_changes"]
      retention_years: 7

    # Privacy controls
    privacy:
      anonymize_data: true
      encrypt_at_rest: true
      encrypt_in_transit: true
      gdpr_compliance: true
