import { NextRequest, NextResponse } from 'next/server';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';

/**
 * Bug Management API
 *
 * GET /api/claude-builder/bugs?projectName=MyProject
 * - Returns all bugs from BUGS.md
 *
 * PATCH /api/claude-builder/bugs
 * - Update bug status
 * - Body: { projectName, bugId, status }
 *
 * DELETE /api/claude-builder/bugs
 * - Delete a bug
 * - Body: { projectName, bugId }
 */

interface Bug {
  id: string;
  title: string;
  description: string;
  severity: 'critical' | 'high' | 'medium' | 'low';
  status: 'open' | 'in_progress' | 'resolved' | 'wont_fix';
  category: string;
  context: {
    page?: string;
    component?: string;
    stackTrace?: string;
  };
  reportedAt: string;
  resolvedAt?: string;
}

function getProjectPath(projectName: string): string {
  const homeDir = os.homedir();
  const sanitizedName = projectName.replace(/[^a-zA-Z0-9-_]/g, '-');
  return path.join(homeDir, 'Projects', 'BuildRunnerProjects', sanitizedName);
}

function parseBugsFile(content: string): Bug[] {
  const bugs: Bug[] = [];
  const bugBlocks = content.split(/^## Bug #/gm).slice(1);

  bugBlocks.forEach((block) => {
    const lines = block.split('\n');
    const idMatch = lines[0]?.match(/^(\d+)/);
    if (!idMatch) return;

    const id = idMatch[1];
    const bug: Partial<Bug> = {
      id,
      context: {},
    };

    // Parse fields
    lines.forEach((line) => {
      const trimmedLine = line.trim();

      if (trimmedLine.startsWith('**Title:**')) {
        bug.title = trimmedLine.replace('**Title:**', '').trim();
      } else if (trimmedLine.startsWith('**Description:**')) {
        bug.description = trimmedLine.replace('**Description:**', '').trim();
      } else if (trimmedLine.startsWith('**Severity:**')) {
        bug.severity = trimmedLine.replace('**Severity:**', '').trim().toLowerCase() as Bug['severity'];
      } else if (trimmedLine.startsWith('**Status:**')) {
        bug.status = trimmedLine.replace('**Status:**', '').trim().toLowerCase().replace(/ /g, '_') as Bug['status'];
      } else if (trimmedLine.startsWith('**Category:**')) {
        bug.category = trimmedLine.replace('**Category:**', '').trim();
      } else if (trimmedLine.startsWith('**Reported:**')) {
        bug.reportedAt = trimmedLine.replace('**Reported:**', '').trim();
      } else if (trimmedLine.startsWith('**Page:**')) {
        bug.context!.page = trimmedLine.replace('**Page:**', '').trim();
      } else if (trimmedLine.startsWith('**Component:**')) {
        bug.context!.component = trimmedLine.replace('**Component:**', '').trim();
      }
    });

    if (bug.id && bug.title) {
      bugs.push(bug as Bug);
    }
  });

  return bugs;
}

function writeBugsFile(projectPath: string, bugs: Bug[]): void {
  let content = '# Bug Tracker\n\n';
  content += '> Auto-generated by Claude Builder error collector\n\n';
  content += '---\n\n';

  bugs.forEach((bug) => {
    content += `## Bug #${bug.id}\n\n`;
    content += `**Title:** ${bug.title}\n`;
    content += `**Description:** ${bug.description}\n`;
    content += `**Severity:** ${bug.severity}\n`;
    content += `**Status:** ${bug.status.replace('_', ' ')}\n`;
    content += `**Category:** ${bug.category}\n`;
    content += `**Reported:** ${bug.reportedAt}\n`;

    if (bug.context.page) {
      content += `**Page:** ${bug.context.page}\n`;
    }
    if (bug.context.component) {
      content += `**Component:** ${bug.context.component}\n`;
    }
    if (bug.resolvedAt) {
      content += `**Resolved:** ${bug.resolvedAt}\n`;
    }

    content += '\n---\n\n';
  });

  fs.writeFileSync(path.join(projectPath, 'BUGS.md'), content, 'utf8');
}

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const projectName = searchParams.get('projectName');

    if (!projectName) {
      return NextResponse.json(
        { error: 'projectName is required' },
        { status: 400 }
      );
    }

    const projectPath = getProjectPath(projectName);
    const bugsPath = path.join(projectPath, 'BUGS.md');

    if (!fs.existsSync(bugsPath)) {
      return NextResponse.json({ bugs: [] });
    }

    const content = fs.readFileSync(bugsPath, 'utf8');
    const bugs = parseBugsFile(content);

    return NextResponse.json({ bugs });
  } catch (error) {
    console.error('[Claude Builder] Get bugs error:', error);
    return NextResponse.json(
      {
        error: 'Failed to fetch bugs',
        details: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    );
  }
}

export async function PATCH(request: NextRequest) {
  try {
    const { projectName, bugId, status } = await request.json();

    if (!projectName || !bugId || !status) {
      return NextResponse.json(
        { error: 'projectName, bugId, and status are required' },
        { status: 400 }
      );
    }

    const projectPath = getProjectPath(projectName);
    const bugsPath = path.join(projectPath, 'BUGS.md');

    if (!fs.existsSync(bugsPath)) {
      return NextResponse.json({ error: 'Bugs file not found' }, { status: 404 });
    }

    const content = fs.readFileSync(bugsPath, 'utf8');
    const bugs = parseBugsFile(content);

    const bug = bugs.find((b) => b.id === bugId);
    if (!bug) {
      return NextResponse.json({ error: 'Bug not found' }, { status: 404 });
    }

    bug.status = status;
    if (status === 'resolved') {
      bug.resolvedAt = new Date().toISOString();
    }

    writeBugsFile(projectPath, bugs);

    return NextResponse.json({ success: true, bug });
  } catch (error) {
    console.error('[Claude Builder] Update bug error:', error);
    return NextResponse.json(
      {
        error: 'Failed to update bug',
        details: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    );
  }
}

export async function DELETE(request: NextRequest) {
  try {
    const { projectName, bugId } = await request.json();

    if (!projectName || !bugId) {
      return NextResponse.json(
        { error: 'projectName and bugId are required' },
        { status: 400 }
      );
    }

    const projectPath = getProjectPath(projectName);
    const bugsPath = path.join(projectPath, 'BUGS.md');

    if (!fs.existsSync(bugsPath)) {
      return NextResponse.json({ error: 'Bugs file not found' }, { status: 404 });
    }

    const content = fs.readFileSync(bugsPath, 'utf8');
    const bugs = parseBugsFile(content);

    const filteredBugs = bugs.filter((b) => b.id !== bugId);

    if (filteredBugs.length === bugs.length) {
      return NextResponse.json({ error: 'Bug not found' }, { status: 404 });
    }

    writeBugsFile(projectPath, filteredBugs);

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('[Claude Builder] Delete bug error:', error);
    return NextResponse.json(
      {
        error: 'Failed to delete bug',
        details: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    );
  }
}
